CREATE TYPE tickets_status AS ENUM ('OPEN', 'IN_PROCESS', 'DONE', 'FAILED');
CREATE TYPE process_status AS ENUM ('PENDING', 'PROCESSING', 'SUCCESS', 'ERROR');
CREATE TYPE process_type AS ENUM ('NETWORK_GRPC', 'BUSINESS', 'CONVERTER', 'NETWORK_FTP');