spring.application.name=converter

# Se voce estiver usando o Artemis de fato (como no seu Docker Compose)
# garanta que estas tambem existam para nao ter erro:
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ami_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Fora o Spring a nao tentar usar o broker interno 'vm'
spring.jms.template.default-destination=training-converter.send_as_json


# 4. Desativa o suporte automatico ao Docker Compose do Spring
# (Ja que voce esta rodando o comando 'docker-compose up' manualmente)
spring.docker.compose.enabled=false