spring.application.name=network-ftp

# Configurações do Broker (Artemis)
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

# Configurações do FTP (Padrão do Dev com Variáveis de Ambiente)
application.ftp.host=${APP_FTP_HOST:localhost}
application.ftp.port=${APP_FTP_PORT:2121}
application.ftp.pasv_ports=${APP_FTP_PASV_PORTS:2222-2225}
application.ftp.username=${APP_FTP_USERNAME:admin}
application.ftp.password=${APP_FTP_PASSWORD:admin}
application.ftp.listener=${APP_FTP_LISTENER:default}
application.ftp.root_directory=${APP_FTP_ROOT_DIRECTORY:ftp_storage}

spring.docker.compose.enabled=false