spring.application.name=network-ftp

spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin


application.ftp.pasv_ports=${APP_FTP_PASV_PORTS:50000-50100}
application.ftp.port=${APP_FTP_PORT:21}
application.ftp.host=${APP_FTP_HOST:localhost}
application.ftp.username=${APP_FTP_USERNAME:ftp_user}
application.ftp.password=${APP_FTP_PASSWORD:ftp_password}
application.ftp.listener=${APP_FTP_LISTENER:default}
application.ftp.root_directory=${APP_FTP_ROOT_DIRECTORY:ftp}

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ami_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true