spring.application.name=projeto-integracao-ami


# Se você estiver usando o Artemis de fato (como no seu Docker Compose)
# garanta que estas também existam para não ter erro:
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

# Força o Spring a não tentar usar o broker interno 'vm'
spring.jms.template.default-destination=training-converter.send_as_json


# 4. Desativa o suporte automático ao Docker Compose do Spring
# (Já que você está rodando o comando 'docker-compose up' manualmente)
spring.docker.compose.enabled=false