spring.application.name=business

# Configurações do Broker (Artemis do seu Docker Compose)
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

# Fila de Entrada (Onde o Cron/Business antigo posta e você consome)
app.queues.input=training-converter.receive_as_json

# Fila de Saída (Onde você posta para o P1/Converter ler)
app.queues.output=training-converter.send_as_json


spring.docker.compose.enabled=false

# Para garantir que o JSON seja serializado corretamente pelo Jackson
#spring.jms.cache.enabled=false