spring.application.name=business

# Configurações do Broker (Artemis do seu Docker Compose)
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=admin
spring.artemis.password=admin

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ami_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# interessante pois estou usando enums, entao o hibernate precisa saber o dialeto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# a linha a seguir e para mostrar o sql que o hibernate esta gerando no console e interessante para debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Fila de Entrada (Onde o Cron/Business antigo posta e você consome)
app.queues.input=training-converter.receive_as_json

# Fila de Saída (Onde você posta para o P1/Converter ler)
app.queues.output=training-converter.send_as_json

# Para garantir que o JSON seja serializado corretamente pelo Jackson
#spring.jms.cache.enabled=false